### PR TITLE
Files ready to go onboard

### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the updated Laura's master branch.

### CODE REVIEW

**Comment by graphicore** [comment]
CAUTION! 5,706 Files changed! :open_mouth: Because the files from `.venv` have been checked in. Also `venv` without a dot is in the `.gitignore` file, which may be a reason why this happened.

**Comment by vv-monsalve** [comment]
> CAUTION! 5,706 Files changed! 😮 Because the files from `.venv` have been checked in. Also `venv` without a dot is in the `.gitignore` file, which may be a reason why this happened.

Yes, I forgot it is like this in the Designer's repo. I'll cancel this and do it from my fork.
Thanks

**Comment by graphicore** [comment]
@vv-monsalve you can also fix  it and `git push --force` the new version. Going a bit deeper into git usage ;-)

**Comment by vv-monsalve** [comment]
Oh, ok, I see. I'll use it next time. Thanks!! :-)

**Pull request closed without merging**
